version: "3.8"
services:

    php:
        build: .
        container_name: lirmi_laravel_php
        volumes:
            - ./src:/var/www/html/

    nginx:
        image: nginx:alpine
        container_name: lirmi_nginx
        volumes:
            - ./src:/var/www/html/
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
            - "443:443"
        depends_on: 
            - php

    postgres:
        container_name: lirmi_postgresql
        image: postgres:alpine
        environment: 
            POSTGRES_USER: lirmi
            POSTGRES_PASSWORD: lirmi
            POSTGRES_DB: lirmi_exercise
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        depends_on: 
            - php

    adminer:
        image: adminer
        container_name: lirmi_adminer
        ports:
            - "8888:8080"
        depends_on: 
            - postgres

volumes:
    pgdata: